### ISSUE TITLE
Login redirecionando para uma rota que não existe

### ISSUE THREAD

**Issue by anajuliarauber** [tech-pro-bem/saude-da-rua-admin-front#13]
Quando é feito o login está sendo redirecionado para uma rota que não existe no App.jsx. Outro ponto a ser discutido é que talvez ao acessar a rota padrão ` '/' ` deveria ser redirecionado ao login

![image](https://user-images.githubusercontent.com/91629999/198894209-12ea6c59-b1be-4c13-bedc-65a7cb6ef77c.png)
![image](https://user-images.githubusercontent.com/91629999/198894217-fd2d8c2c-f67a-4005-a499-e40c35ddb940.png)

**Comment by lucas-lm** [comment]
@anajuliarauber, pode mudar o `navigate("/home")` para `navigate("/")` na #12.

---

Sobre o redirecionamento ao acessar a rota raiz (`"/"`), não deveria haver o redirecionamento direto, mas sim uma regra de proteção de rotas. Tem duas estratégias que eu consideraria (caso não tenha nenhuma orientação vinda de UX), sendo que ambas começam com a checagem de autenticação do usuário. 

A primeira opção seria:
* Usuário está autenticado: Exibe a página acessada
* Usuário não está autenticado
  1. Redireciona para página de login 
  2. Segue o fluxo de login natural

A segunda opção:
* Usuário está autenticado: Exibe a página acessada
* Usuário não está autenticado 
  1. Guarda o estado da página acessada (path, parâmetros etc.)
  2. Redireciona para página de login
  3. Redirecionar para página acessada originalmente com seus parâmetros ao realizar login com sucesso

A segunda opção é melhor em termos de UX, mas adiciona um maior nível de complexidade (principalmente pensando em edge cases), por isso recomendo que siga com a primeira por ser mais simples.

__Sobre a implementação:__

Já temos um componente de Layout Autenticado, então só precisamos adicionar essa lógica de checagem de autenticação nesse componente e continuar usando ele como wrapper de rotas protegidas.

@tech-pro-bem/squad-admin
